accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .import views

app_name = 'accounts'


urlpatterns = [
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path("profile/", views.ProfileView.as_view(), name='profile'),
    path("profile/edit/<pk>/",
         views.ProfileEditView.as_view(),
         name='profile_edit'),
    path("user/<str:username>", views.user_detail, name='user_profile'),

    path("register/", views.register, name='register')
]

forum/urls.py
from django.urls import path
from .import views

app_name = 'forum'


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('add/', views.AddNewTopicView.as_view(), name='add_topic'),
    path('detail/<slug>', views.TopicDetailView.as_view(), name='detail'),
    path("category/<slug>", views.CategoryListView.as_view(), name='category_list'),
    path("tag/<slug>", views.TagListView.as_view(), name='tag_list'),

]

pyforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("forum.urls", namespace='forum')),
    path("accounts/", include("accounts.urls", namespace='accounts')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    address = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to='user_images/', blank=True)
    bio = models.TextField(blank=True)
    facebook_link = models.URLField(verbose_name="Facebook link", blank=True)
    instagram_link = models.URLField(verbose_name="Instagram link", blank=True)
    telegram_link = models.URLField(verbose_name="Telegram link", blank=True)

    def get_full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return "No fullname"

    def __str__(self):
        return str(self.username)

forum/models.py
from django.db import models
from accounts.models import User
from django.template.defaultfilters import slugify
# Create your models here.

from django_quill.fields import QuillField


class Category(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name_plural = 'Categories'


class Tag(models.Model):
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, unique=True)

    def __str__(self):
        return str(self.name)


class Topic(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    body = QuillField()
    top = models.BooleanField(default=False)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, related_name='category')
    tag = models.ManyToManyField(Tag, related_name='tag')
    published = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name='topics')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Topic, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = QuillField()

    def __str__(self):
        return str(self.user.username)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SimpleUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib import messages
from django.conf import settings
from .models import User
# Create your views here.
from .forms import SimpleUserCreationForm


class ProfileView(LoginRequiredMixin, TemplateView):

    template_name = 'registration/profile.html'


class ProfileEditView(UpdateView):
    model = User
    template_name = "registration/user_form.html"
    fields = ["first_name", "last_name", "image", "bio", "address",
              "facebook_link", "instagram_link", "telegram_link"]
    success_url = reverse_lazy("accounts:profile")


def register(request):
    form = SimpleUserCreationForm()
    if request.method == "POST":
        form = SimpleUserCreationForm(request.POST)
        if form.is_valid():
            u = form.save()
            try:
                group = Group.objects.get(name="default_user")
                group.user_set.add(u)
            except Exception as er:
                # raise
                print(er)
            print("OK")
            authenticate(u)
            message = "Successfully !"
            messages.add_message(request, messages.SUCCESS, message)
            return redirect("/")
        else:
            message = "Error !"
            messages.add_message(request, messages.ERROR, message)
            return render(request, "registration/register.html", {"form": form})

    return render(request, "registration/register.html", {"form": form})


def user_detail(request, username):
    user = get_object_or_404(User, username=username)

    context = {
        "user": user
    }
    return render(request, "registration/profile.html", context=context)

forum/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from .models import Category, Tag, Topic, Comment


class HomePageView(ListView):
    model = Topic
    paginate_by = 10
    context_object_name = "topics"
    template_name = "index.html"

    def get_queryset(self):
        topics = Topic.objects.all().select_related("category", "author")
        return topics


class AddNewTopicView(LoginRequiredMixin, CreateView):
    model = Topic
    fields = ["title", "category", "tag", "body"]
    success_url = "/accounts/profile/"

    def form_valid(self, form):
        print(dir(form.instance))
        form.instance.author = self.request.user
        return super().form_valid(form)


class TopicDetailView(DetailView):
    queryset = Topic.objects.select_related("category", "author")
    # queryset = Topic.objects.prefetch_related("tag")
    model = Topic

    # def get_queryset(self):
    #     topic = Topic.objects.get(slug=self.kwargs["slug"])
    #     return topic


class CategoryListView(ListView):
    model = Topic

    def get_queryset(self):
        # original qs
        qs = super().get_queryset()
        # filter by a variable captured from url, for example
        return qs.filter(category__slug=self.kwargs['slug'])


class TagListView(ListView):
    model = Topic

    def get_queryset(self):
        # original qs
        qs = super().get_queryset()
        # filter by a variable captured from url, for example
        return qs.filter(tag__slug=self.kwargs['slug'])

templates/forum/topic_detail.html
{% extends '../wrapper.html' %}
{% load static %}
{% block content %}
{{form.media}}
<!-- title  -->
{% block title %}
<title>
    Topic - {{object.title}}
</title>
{% endblock title %}
<br><br>
<section>
    <div class="container">
        <div class="grid">
            <article>
                <p>
                    <b>Category</b>:
                    <a href="">{{object.category}}</a>
                </p>
                <p>
                    <b>Tags</b>:
                    {% for tag in object.tag.all %}
                    <a href="{% url 'forum:tag_list' tag.slug %}">{{tag.name}}</a>
                    {% endfor %}
                </p>
                <h3>{{object.title}}</h3>


                <p>{{object.body.html|safe}}</p>
                <p class="grid">
                    <span>
                        <ion-icon name="eye-outline"></ion-icon> {{topic.views}}
                    </span>

                    <span><ion-icon name="person-outline"></ion-icon>{{topic.author}}</span>
                </p>
                <a href="/" role="button">Back to topics</a>
            </article>
        </div>
    </div>
</section>

{% endblock %}

templates/forum/topic_form.html
{% extends '../wrapper.html' %}
{% load static %}
{% block content %}
{{form.media}}
<!-- title  -->
{% block title %}
<title>
    Add new topic -
    {% if request.user.first_name %}
    {{request.user.first_name}}
    {% else %}
    {{request.user.username}}
    {% endif %}
</title>
{% endblock title %}
<br><br>
<section>
    <div class="container">
        <div class="grid">
            <form action="" method="post">
                {{form}}
                {% csrf_token %}
                <input type="submit" value="Add" role="button">
            </form>
        </div>
    </div>
</section>

{% endblock %}

templates/forum/topic_list.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="grid">
            {% for topic in object_list %}
            <div class="topics">
                <div class="topic">
                    <a href="{% url 'forum:category_list' topic.category.slug %}">{{topic.category}}</a>
                    <br>
                    <h5>
                        <a href="{% url 'forum:detail' topic.slug %}">
                            {{topic.title}}
                        </a>
                    </h5>
                    <br>
                    <p class="grid">
                        <span>
                            <ion-icon name="eye-outline"></ion-icon> {{topic.views}}
                        </span>

                        <span><ion-icon name="person-outline"></ion-icon>{{topic.author}}</span>
                    </p>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/index.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="grid">
            {% for topic in topics %}
            <div class="topic">
                <article>
                    <h3>{{topic.title}}</h3>
                    <p>{{topic.body|truncatewords:'25'}}</p>
                </article>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="dark">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'pico.min.css' %}">
    <link rel="stylesheet" href="{% static 'pico.classless.min.css' %}">
    {% block title %}
    <title>Python forum</title>
    {% endblock title %}
</head>

<body>

    <div class="container">
        <nav>
            <ul>
                <li>
                    <a href="/">
                        <strong>forum.py</strong>
                    </a>
                </li>
            </ul>
            <ul>
                <li>
                    <a href="#">
                        <ion-icon size="large" name="search-outline"></ion-icon>
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'accounts:profile' %}">
                        <ion-icon size="large" name="person-outline"></ion-icon>
                    </a>
                </li>
                <li>
                    <a href="{% url 'accounts:logout' %}">
                        <ion-icon size="large" name="log-out-outline"></ion-icon>
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'accounts:login' %}">
                        <ion-icon size="large" name="log-in-outline"></ion-icon>
                    </a>
                </li>
                {% endif %}

                <li>
                    <a href="#" onclick="themeSwitch(this)">
                        <ion-icon size="large" name="sunny-outline"></ion-icon>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

    {% block content %}

    {% endblock %}
    <script src="{% static 'script.js' %}"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>